apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-conf
data:
  env: |
    MONGO_DSN=mongodb://root:root@mongodb/nest?authSource=admin
    KAFKA_CLIENT_ID=code-delivery
    KAFKA_BROKER=pkc-4yyd6.us-east1.gcp.confluent.cloud:9092
    KAFKA_CONSUMER_GROUP_ID=code-delivery
    KAFKA_SASL_USERNAME=6Q4KTSAVK2R34JXA
    KAFKA_SASL_PASSWORD=lytkrvs3P8XK9f3zOjd2IP1xrobu4tN4JKC8gnVeskSUvFvDbqTworLFhabh1yPY
